name: Release
on:
  push:
    paths:
      - 'HeliosLauncher/package.json'
    branches:
      - master
      - 'prerelease/*'
    tags-ignore:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Get version
        id: get-version
        shell: bash
        run: |
          VERSION=$(node -p "require('./HeliosLauncher/package.json').version")
          BRANCH=${GITHUB_REF#refs/heads/}
          IS_PRERELEASE=${{ contains(github.ref, 'prerelease/') }}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "is_prerelease=$IS_PRERELEASE" >> $GITHUB_OUTPUT

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd HeliosLauncher
          npm install

      - name: Update release type for prerelease
        if: ${{ contains(github.ref, 'prerelease/') }}
        run: |
          cd HeliosLauncher
          jq '.build.publish[0].releaseType = "prerelease"' package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Build/Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: false
          package_root: HeliosLauncher
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
          DEBUG: electron-builder

      - name: List dist directory
        run: |
          cd HeliosLauncher/dist
          ls -la

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.os }}
          path: |
            HeliosLauncher/dist/*
            !HeliosLauncher/dist/builder-debug.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Get version
        id: get-version
        shell: bash
        run: |
          VERSION=$(node -p "require('./HeliosLauncher/package.json').version")
          IS_PRERELEASE=${{ contains(github.ref, 'prerelease/') }}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "is_prerelease=$IS_PRERELEASE" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Delete existing prerelease tag
        if: ${{ steps.get-version.outputs.is_prerelease }}
        run: |
          git tag -d prerelease || true
          git push origin :refs/tags/prerelease || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 정식 릴리즈일 때 latest 태그 업데이트
      - name: Update latest tag
        if: ${{ !steps.get-version.outputs.is_prerelease }}
        run: |
          git tag -f latest
          git push -f origin latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.get-version.outputs.is_prerelease && format('Pre-release v{0}', steps.get-version.outputs.version) || format('Release v{0}', steps.get-version.outputs.version) }}
          tag_name: ${{ steps.get-version.outputs.is_prerelease && 'prerelease' || format('v{0}', steps.get-version.outputs.version) }}
          draft: false
          prerelease: ${{ steps.get-version.outputs.is_prerelease }}
          files: |
            artifacts/dist-macos-latest/!(builder-debug.yml)
            artifacts/dist-windows-latest/!(builder-debug.yml)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # latest 릴리즈의 기존 자산 삭제
      - name: Delete latest release assets
        if: ${{ !steps.get-version.outputs.is_prerelease }}
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 0
          delete_tags: false
          delete_tag_pattern: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 정식 릴리즈일 때 latest 릴리즈도 생성
      - name: Create latest release
        if: ${{ !steps.get-version.outputs.is_prerelease }}
        uses: softprops/action-gh-release@v1
        with:
          name: Latest Release
          tag_name: latest
          draft: false
          prerelease: false
          files: |
            artifacts/dist-macos-latest/!(builder-debug.yml)
            artifacts/dist-windows-latest/!(builder-debug.yml)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
